// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhH3I0VtKmsOhJtunuE8yE9uFk1WdYkY',
    appId: '1:112210040014:web:f6b2f844f3897b9575ac9f',
    messagingSenderId: '112210040014',
    projectId: 'ridebookingapp-5355a',
    authDomain: 'ridebookingapp-5355a.firebaseapp.com',
    storageBucket: 'ridebookingapp-5355a.firebasestorage.app',
    measurementId: 'G-D7ZWEDMMW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArScWDM_p-IsPEWapGsLuhExRBXQD3ZNc',
    appId: '1:112210040014:android:45d61741e98c41b575ac9f',
    messagingSenderId: '112210040014',
    projectId: 'ridebookingapp-5355a',
    storageBucket: 'ridebookingapp-5355a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUHmXibpb_hWTSsRZ8V-QiwZyD2-YSUU',
    appId: '1:112210040014:ios:b8ee6e708612665375ac9f',
    messagingSenderId: '112210040014',
    projectId: 'ridebookingapp-5355a',
    storageBucket: 'ridebookingapp-5355a.firebasestorage.app',
    iosBundleId: 'com.example.ridebooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUHmXibpb_hWTSsRZ8V-QiwZyD2-YSUU',
    appId: '1:112210040014:ios:b8ee6e708612665375ac9f',
    messagingSenderId: '112210040014',
    projectId: 'ridebookingapp-5355a',
    storageBucket: 'ridebookingapp-5355a.firebasestorage.app',
    iosBundleId: 'com.example.ridebooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLhH3I0VtKmsOhJtunuE8yE9uFk1WdYkY',
    appId: '1:112210040014:web:a537f91b0a77319675ac9f',
    messagingSenderId: '112210040014',
    projectId: 'ridebookingapp-5355a',
    authDomain: 'ridebookingapp-5355a.firebaseapp.com',
    storageBucket: 'ridebookingapp-5355a.firebasestorage.app',
    measurementId: 'G-EH9S7XT2LK',
  );
}
